// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeIcHGzgm5VWuzhzlx9uXF9vbnuGHz-F4',
    appId: '1:582338253612:web:e19305ba6696a88a349289',
    messagingSenderId: '582338253612',
    projectId: 'instantgram-3a415',
    authDomain: 'instantgram-3a415.firebaseapp.com',
    storageBucket: 'instantgram-3a415.appspot.com',
    measurementId: 'G-7XSGRREEV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeQojoFtB47lmu42pqK7UlH8DgmVLSau4',
    appId: '1:582338253612:android:da30c5def0de6ef4349289',
    messagingSenderId: '582338253612',
    projectId: 'instantgram-3a415',
    storageBucket: 'instantgram-3a415.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnWsiJKxA-MxsczoLJGS3OkPjr2vw-Dmo',
    appId: '1:582338253612:ios:66f4df524163ccbe349289',
    messagingSenderId: '582338253612',
    projectId: 'instantgram-3a415',
    storageBucket: 'instantgram-3a415.appspot.com',
    iosClientId: '582338253612-th3rqp907vk4o02k6d1gjs1jguh3cfgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.instantgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnWsiJKxA-MxsczoLJGS3OkPjr2vw-Dmo',
    appId: '1:582338253612:ios:06d15afa7ca4d0fb349289',
    messagingSenderId: '582338253612',
    projectId: 'instantgram-3a415',
    storageBucket: 'instantgram-3a415.appspot.com',
    iosClientId: '582338253612-0nk6o2stn58smb9osm78dlpj8ap95l8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.instantgram.RunnerTests',
  );
}
